### ISSUE TITLE
Implement Suture.create :call_both

### ISSUE THREAD

**Issue by searls** [testdouble/suture#41]
When `:call_both` is set (intended for staging environments), the following is required:

- [x] both `:new` and `:old` code paths must be set
- [x] call_both and records_calls are mutually exclusive (ensure #15 includes a check for this)

And the following happens:

- [x] the `:new` path is called and its result is held
- [x] If #40's set to have a clean-between callable, call it
- [x] the `:old` path is called and its result is held
- [x] If #40's set to have a clean-after callable, call it
- [x] the two results are compared using whatever `comparator` applies to the seam
- [x] If the two results match, the new result is returned
- [x] If they don't match and #39 is set to raise, then raise an error (either way log a warning)
